### PR TITLE
 Remove prepended `text:` from floData sent from UI

### PR DESCRIPTION
**Pull request by OstlerDev**
Currently `text:` is prepended to `floData` sent via the Flo-qt UI. Having that data prepended creates a blocking issue for developers wishing to quickly test sending of `floData` using the QT wallet UI.

This change simply removes that prepended text :)

### CODE REVIEW

**Comment by cchrysostom** [comment]
Yea! This is a pet peeve of mine. Be aware, this change will need to get communicated to current app developers because I imagine they have logic to remove `text:` before parsing json text.

**Comment by bitspill** [comment]
> Be aware, this change will need to get communicated to current app developers because I imagine they have logic to remove `text:` before parsing json text.

Apps should already be checking if the text prefix exists before attempting to strip it since they are likely using RPC which doesn't add it resulting in processing a mix of have's/have-not's and I'd anticipate this being a fairly clean change but we can definitely note it on the next release

**Comment by bitspill** [comment]
I kind of like the `text:` prefix because it makes scanning for user submitted floData easy such as the below snippet, without the prefix it complicates isolating notes from application data

```
 3167884 1aafe49ceeb81355368e2461190ef58396c3fbe378ebf5f980ce5825b8b3cc52 - text:You will be indepenently wealthy before the end of the month of december 2018. 
 3182822 0dcb00093db99daa66948ab7e59f235021a7072771fc873c14f490a2d5a172f3 - text:Go with the Flo everyone, big shout out to all the peeps in the telegram group
 3184065 b1f1c5ee9b763c580ef4b4216ee35b17d3860439cf60120a15d1c500b23b4106 - text:FLOmo #GoWithTheFlo
 3184832 60fae5094326346d36b7ece4dd4842773d917cabd49c2824774ecdcce92baf96 - text:transfer
 3189805 0f78c3fe76cd34c38af19b59521171a65277e6e79b5ed68c17cf993ca102d594 - text:hope you eat well Joey :-)
 3199920 77d3acd5f879e4f75df6649e6c99e48a8fe75d274656a678d118237f3b9fdbfa - text:HAPPY FLO HALVENING TO THE FLOMIES ON ONE NINE TWENTY NINETEEN
 3216557 fa37fb5c524cd5d19c432d6d67ff791ac1daf5a44cef9f21ad92aa007ba5f259 - text:#GoWithTheFLO Trezor Donation @FLOBLOCKCHAIN
 3218604 670c0b9ad7c2959362fbaefa343dde22dc5e4932befbb9470cb35df6c67c3fc2 - text:Hello world
 3218622 614ae878b37f24695f03fc86f4e3201e7e888c9ccf528231d7741e496ea88882 - text:Hello world!
 3218737 96b2ec7c7c222ebd5b8d6d9ce6a586ac564560c7c3adff004a62c58f526f3184 - text:Flo is dopeee
 3219324 0dfaf55ba5e8a7c215f1ceb56ce06e0fe683a5af0fa9f387d9ef9f82e7e62482 - text:Hello, flobot. It's cloudy and 42 degrees in Salt Lake City, now. What's it like for you?
 3219444 8ce40c8e9b50354a62e678c88e464dd34e3a8eb37cc2d32027059620dfa5b5c8 - text:Are we there, yet?
 3220858 b7fe2506dd0078ea496c7a1463a9e14d7c138913fb5b2aeae581ad4be149c59a - text:for Joey  <3
 3223355 59fb321ffca468e1df9d44270eece11ce92b6266e87c169520769ff3786813f1 - text:Funding of Contract Id 33
 3223941 dfca47e18457fe69e58e151c6e8a9d70e28b590dd62120bd8690319925c38965 - text:yo whats good
 3224160 b33856509fea724a3805ae200a8f70136e11371ec2c9d1d89af779843f17e7ed - text:137
 3224230 6a39a905f453586a84ebb5758db956ae70e45c2f737ffd055aa1b67769d4ec53 - text:Oliver-Isi-Rees-Flo-Vienna-23.1.2019-00:09:04-BUSSI
 3228078 ed94320aa8d6bc040e775247f689c7cf3bcd207bce7968dfdcaf45b9dacf6ba1 - text:Cancel
 3228148 319fec81b7798a0ce76e29f66b63921ae38f0c1c4a31ba6d62f29ae05964365d - text:cuz it's urgent
 3234472 0c57ac4314c31c5673e0687a2ffc56d17516afe3a8661e9582ad7fd9b8f4d75d - text:Fennex smart contract funds
 3235799 b8250a135fcb1d585bd16f94acba463d2011028b35d0e309ba58aa54677b74ac - text:CoxFTW was here
 3236777 1d6c8aee5d252fbfb853f764d078a6b3c4f2c3c14c78a623cbff47c55d87dd92 - text:the world is flat
 3236785 54e8ee3e044b4153c8658fc1dc6eac1c31dac90fbf0762400d2eafd8618396ba - text:YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS YOU SHALL BE AS GODS 
 3238858 0389e00ad00a0f2c603deca2c067638736bfc34f7c968318ee5a73ef9deb03ba - text:This is a test message to demonstrate FLO data. Its pretty cool!!
 3238867 834e2e6163dd56dec37a86c5d779be9569523609fe20cd5c9f78fc71e4d43392 - text:Hey, this a message to demonstrate FLO data. Its pretty cool!!
```

**Comment by cchrysostom** [comment]
Yes, helpful for searching, but shouldn't special tags like `text:` be defined by the author of the floData contents?

**Comment by bitspill** [comment]
> Yes, helpful for searching, but shouldn't special tags like `text:` be defined by the author of the floData contents?

The `text:` prefix is only prepended if sent via the QT interface where a manual send is created by an end user, they'll never manually add `text:` -- RPC calls do not include the prefix and offer complete control to the application

**Comment by daviortega** [comment]
I vote to remove it.

Even if @bitspill is right, people can mock text into a non-QT-wallet and send the text anyways... which would completely undermine the only utility for it.

**Pull request merged**
